### ISSUE TITLE
Private modules can be fetched with go list

### ISSUE THREAD

**Issue by Crocmagnon** [nieomylnieja/go-libyear#56]
## What happens
```console
$ go-libyear --go-list ./go.mod
Error: private module path: 'example.com/module' cannot be handled by any supported VCS [git]
```

where `example.com/module` is an internal module, on a domain configured in `GOPRIVATE`.

## Expected behavior
When commenting this block:
https://github.com/nieomylnieja/go-libyear/blob/5dc2dd4a0ce4cc12c71fd0801f59c97c021da59b/command.go#L108-L115

I'm getting the behavior I'd expect:
```console
$ go-libyear --go-list ./go.mod
# ... (prints proper report)
```

## Notes
* It looks like `go-libyear` tries to detect whether it can fetch the repo with git without even checking if it's running with `go-list`.
* I don't know whether _all_ private repos can be accessed with `go list`.

**Comment by nieomylnieja** [comment]
Yeah, this is a clear oversight on my part and a correct identification of the the issue :)

I'll fix it today. Thanks!

**Comment by nieomylnieja** [comment]
The issue should be fixed in https://github.com/nieomylnieja/go-libyear/releases/tag/v0.4.2.

Let me know if it works for you now :)

**Comment by Crocmagnon** [comment]
It does! Thanks 🙂
